String baseApi = 'https://api.themoviedb.org';

List khodam = [
  "Sepeda lipat",
  "Sandal Jepit",
  "Kecoa Terbang",
  "Cicak EE",
  "Knalpot RX King",
  "Ular Python",
  "Naga Bonang",
  "Monyet Cantik",
  "Harimau Putih",
  "Buaya Darat",
  "Sepeda Kebalik",
  "Harimau Belang",
  "Tikus Kejebur",
  "Burit Ega",
  "Naga Putih",
  "Kera Sakti",
  "Tokek Cililin",
  "Korong Kucing",
  "Sepeda Jokowi",
  "Bobi",
  "Kucing Kawin",
  "Dewi Kuang In",
  "Biksu Tong",
  "Tuyul Mulet",
  "Pocica",
  "Donat Jco",
  "Tuyul Gondrong",
  "Seblak Ceker",
  "Capibara",
  "Pantai Panci",
  "Kursi Birahi",
  "Macbook M3 Pro",
  "Kuda Kejepit",
  "Tutup Kejepit",
  "Botol Yakult",
  "Pecinta Code Error",
  "Cumi Github",
  "Kodok Ngangkang",
  "Cumi Nunggi",
  "Abe Cekut",
  "Kamera Advan",
  "Kodok Borok",
  "Tikus Pejet",
];
